CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    phone VARCHAR(32),
    phone_country VARCHAR(8) NOT NULL DEFAULT 'US',
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(16) NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(32) NOT NULL CHECK (category IN (
        'events', 'restaurants', 'health', 'education', 'communities'
    )),
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    state VARCHAR(64) NOT NULL,
    city VARCHAR(128) NOT NULL,
    venue VARCHAR(255),
    event_date DATE,
    start_time VARCHAR(16),
    end_time VARCHAR(16),
    organizer_id BIGINT NOT NULL REFERENCES users(id),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(32),
    contact_phone_country VARCHAR(8) NOT NULL DEFAULT 'US',
    image_url VARCHAR(512),
    logo_url VARCHAR(512),
    attachment_url VARCHAR(512),
    attachment_name VARCHAR(255),
    status VARCHAR(16) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ad_inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(32),
    tier VARCHAR(64) NOT NULL,
    message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_listings_category ON listings(category);
CREATE INDEX idx_listings_state ON listings(state);
CREATE INDEX idx_listings_date ON listings(event_date);
CREATE INDEX idx_listings_status ON listings(status);
