spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
  flyway:
    baseline-on-migrate: false

server:
  error:
    include-message: never
    include-stacktrace: never

logging:
  level:
    root: INFO
    org.springframework.web: WARN
